### ISSUE TITLE
Colors in output disrupt line alignment

### ISSUE THREAD

**Issue by counterbeing** [thoughtbot/pick#100]
I had a script working in v1.2.1 that is useful for selecting from recently checked out git branches. I was using color to divide some of the columns. I've narrowed the issue down to being color specifically. This occurs in both bash and zsh for me. Here's an example that produces odd output:

```bash
RED='\033[0;31m'
NC='\033[0m'
printf "${RED}pick${NC} is the handiest\n${RED}pick${NC} is the handiest\n${RED}pick${NC} is the handiest\n${RED}pick${NC} is the handiest\n${RED}pick${NC} is the handiest\n${RED}pick${NC} is the handiest\n${RED}pick${NC} is the handiest\n${RED}pick${NC} is the handiest\n" | pick
```

So, you can see we've created a list of colorized items to pipe to pick. Here is what the output looks like on my system for some reason. The issue first came up after installing v1.3.

![image](https://cloud.githubusercontent.com/assets/239798/13035189/a08aad78-d2fe-11e5-9b50-d21d38d622ea.png)

Thank you guys so very much for this great tool, I've applied it to all sorts of things, and makes my work merrier several times a day. You guys rock!

**Comment by mptre** [comment]
Thanks for the extensive report. This is a regression from the latest changes to
the way strings are outputted. A quick debug reveled the following: the length
of a choice is currently calculated as the number of bytes until a new line
character occurs. It does not distinguish between printable characters and
escape sequences such as color codes. The code prior v1.3.0 explicitly moved the
cursor to the next line before printing the next choice as opposed of the
current solution which relies on the fact that printing a character when the
cursor is positioned at last column will move the cursor to the next line. Since
escape sequences is counted as printable characters the cursor won't end up at
the last column. A quick solution would be to print a new line character before
printing the next line.

On Sun, Feb 14, 2016 at 09:40:39AM -0800, Cory Logan wrote:
> I had a script working in v1.2.1 that is useful for selecting from recently checked out git branches. I was using color to divide some of the columns. I've narrowed the issue down to being color specifically. This occurs in both bash and zsh for me. Here's an example that produces odd output:
> 
> ```bash
> RED='\033[0;31m'
> NC='\033[0m'
> printf "${RED}pick${NC} is the handiest\n${RED}pick${NC} is the handiest\n${RED}pick${NC} is the handiest\n${RED}pick${NC} is the handiest\n${RED}pick${NC} is the handiest\n${RED}pick${NC} is the handiest\n${RED}pick${NC} is the handiest\n${RED}pick${NC} is the handiest\n" | pick
> ```
> 
> So, you can see we've created a list of colorized items to pipe to pick. Here is what the output looks like on my system for some reason. The issue first came up after installing v1.3.
> 
> ![image](https://cloud.githubusercontent.com/assets/239798/13035189/a08aad78-d2fe-11e5-9b50-d21d38d622ea.png)
> 
> 
> Thank you guys so very much for this great tool, I've applied it to all sorts of things, and makes my work merrier several times a day. You guys rock!
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/thoughtbot/pick/issues/100

-- 
:wq

**Comment by counterbeing** [comment]
Thanks for the very detailed response :)

I tried sticking a `\n` in front of each of the lines, but still ran into the same issue, but maybe I didn't understand something in your proposed workaround.

Thanks again!

**Comment by mptre** [comment]
On Mon, Feb 15, 2016 at 02:22:20PM -0800, Cory Logan wrote:
> Thanks for the very detailed response :)
> 
> I tried sticking a `\n` in front of each of the lines, but still ran into the same issue, but maybe I didn't understand something in your proposed workaround.
> 
> Thanks again!
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/thoughtbot/pick/issues/100#issuecomment-184420905

Sorry for being unclear, I was refering to the actual implementation.

-- 
:wq

**Comment by counterbeing** [comment]
Gotcha :) Well, I've removed the colors for now, and my script still does it's duty. All the better now that the results remain sorted! Thanks for that patch. Looking forward to getting color back one of these days. You guys rock!

**Comment by calleerlandsson** [comment]
Hey @counterbeing, thanks for reporting this, and thanks @mptre for debugging it! I have submitted #102 to fix this. Feel free to try the branch out and take a look at the code!

By the way, instead of resetting all attributes with `\033[0m` you might want to use `\033[39m` to reset only the foreground color. This will make underlining matches work properly.

Another note, setting the foreground color effectively exits standout mode causing the highlighting of the currently selected choice to not work properly. I've tried to come up with a fix for this but haven't succeeded yet. Suggestions on how to solve this are much appreciated!
