### ISSUE TITLE
Stable sort option

### ISSUE THREAD

**Issue by campadrenalin** [thoughtbot/pick#107]
The default sort is good for some use cases, but if you're trying to filter things that are in chronological order (like git commits) it becomes a bit lackluster. Having an option for stable sorting would be very valuable for picking things from an externally-ordered list.

**Comment by mptre** [comment]
I had the same concern, especially regarding Git commits since a newer
commit with a lower score is often more relevant than a older commit
with a higher score. I've been experimenting with weights (boosting
factors) for each choice (line), with the formula `log(N/offset)' where
N begin the number of bytes in the input and offset the relative byte
offset for the given line. The factor works like a inverted line offset,
thus lines near the start of the input will receive a greater weight
compared to lines closer to the end of the input. It might consider
submitting my changes upstream if people find it useful.

**Comment by campadrenalin** [comment]
If you submit it as a PR here, I'll definitely build and use it.

**Comment by calleerlandsson** [comment]
Hey @campadrenalin, thanks for your feedback!

Could a filter-only mode that turned off sorting and simply filtered the list be a possible solution to this?

@mptre that's an interesting idea! It's hard to envision what results that would yield but I'd be very happy to try it out! What are your thoughts on a filter-only mode? How do you think it would compare to a weighted sorting?

**Comment by campadrenalin** [comment]
Filter-only is exactly what I'm looking for (for this use case), whether
it's implemented with custom weighting or not.

**Comment by mptre** [comment]
On Sat, Mar 26, 2016 at 01:17:27PM -0700, Calle Erlandsson wrote:
> Hey @campadrenalin, thanks for your feedback!
> 
> Could a filter-only mode that turned off sorting and simply filtered the list be a possible solution to this?
> 
> @mptre that's an interesting idea! It's hard to envision what results that would yield but I'd be very happy to try it out! What are your thoughts on a filter-only mode? How do you think it would compare to a weighted sorting?

I like the idea of filter-only since it's simpler. But I could push the
weighted solution later for testing and evaluation.

> 
> ---
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/thoughtbot/pick/issues/107#issuecomment-201925631

-- 
:wq

**Comment by calleerlandsson** [comment]
Cool! If any of you want to work on this, feel free to do so. If not, I'll look into it when I get some time over!
