### ISSUE TITLE
Add support for picking multiple choices

### ISSUE THREAD

**Issue by TwistingTwists** [thoughtbot/pick#122]
Can `pick` be used to pick multiple lines ? May be run `pick -i` (pick interactive - to pick as many as we want?)

**Comment by calleerlandsson** [comment]
Pick doesn't have that functionality.

What is your use-case for picking multiple choices?

**Comment by TwistingTwists** [comment]
I want to use `pick` to save some commands from `~/.bash_history` file into a new file.

**Comment by calleerlandsson** [comment]
@TwistingTwists Thanks for explaining.

I think this will require the following changes:

- Adding a new keybinding for selecting a choice without exiting
- Storing information about whether a choice is selected or not inside the data structure rather than as offset into the array of choices
- When exiting looping over the array of choices printing all of the selected ones rather than just printing one

Possible issues I see with this feature are:

- Added complexity
- Ordering the output choices

If you want to work on this, I'm happy to answer your questions and review PRs.

**Comment by justgage** [comment]
Although this may not be satisfactory, you could just use something like `grep` for this. 

Also, you could have a way of simply saving all results of a query instead of just one by passing in a command line argument. Not sure if that's the functionality you're looking for though @TwistingTwists.  However any of these would add a lot of complexity.

**Comment by calleerlandsson** [comment]
I'll close this issue for now. Feel free to re-open it if you'd want to work on it, @TwistingTwists.

**Comment by nereusx** [comment]
I am codding this now.
Reason/example, using shell script install / uninstall packages through pick in void-linux (xbps-install/xbps-remove)
