### ISSUE TITLE
Homebrew formula checksum mismatch

### ISSUE THREAD

**Issue by christoomey** [thoughtbot/pick#39]
The homebrew formula currently has the wrong sha1 checksum.

``` sh
$ brew install pick                                                                                                                                
==> Installing pick from thoughtbot/homebrew-formulae
==> Downloading https://github.com/thoughtbot/pick/releases/download/v1.1.0/pick-1.1.0.tar.gz
Already downloaded: /Library/Caches/Homebrew/pick-1.1.0.tar.gz
Error: SHA1 mismatch
Expected: cec167acc776065c055ab13a918d4e0300dca2f8
Actual: 8b035e64cc5faea407e73cce01ca039e3ce3b4ac
Archive: /Library/Caches/Homebrew/pick-1.1.0.tar.gz
To retry an incomplete download, remove the file above.
```

I wonder if the `@DIST_SHA@` directive in the homebrew template needs to specify the `.tag.gz` file?

**Comment by c0nspiracy** [comment]
I'm experiencing the same problem.

**Comment by bigbam505** [comment]
I fixed the problem locally for me by just following the following steps.

First I ran the following:
`brew edit pick`

Then changed the following line:
```
- sha1 "cec167acc776065c055ab13a918d4e0300dca2f8"
+ sha1 "8b035e64cc5faea407e73cce01ca039e3ce3b4ac"
```

Then ran the following again:
`brew install pick`



It looks like someone just type-oed the sha1 hash because when I actually download the file from that url and run `shasum -a 1 pick-1.1.0.tar.gz` I get this hash `8b035e64cc5faea407e73cce01ca039e3ce3b4ac`

**Comment by teoljungberg** [comment]
Closed by https://github.com/thoughtbot/homebrew-formulae/commit/60afac6807473d9288be6f899030da12c9721027
