### ISSUE TITLE
Does not retain order of results

### ISSUE THREAD

**Issue by eavgerinos** [thoughtbot/pick#50]
Steps to reproduce

- `cat file | pick`
- Notice the ordering of the results
- Add some input
- Remove it
- The ordering of the results is not the original anymore

**Comment by calleerlandsson** [comment]
Hey @eavgerinos, thanks for reporting this.

I think this is because the conditional on [this line](https://github.com/thoughtbot/pick/blob/92b3fbadfc92a7c786623f847f1ad137f5d3fa01/src/choices.c#L78) only checks the score of choices. By also sorting choices with the same score alphabetically, the order would be deterministic.

Unless someone beats me to it, I'll look into this as soon as I can.
