### ISSUE TITLE
Mapping to "cancel"

### ISSUE THREAD

**Issue by rosshadden** [thoughtbot/pick#51]
As it is right now, `control-c` exits.  However it exits with a non-zero status code (which is expected), and thus if another program had launched `pick` (such as [`tig`](https://github.com/jonas/tig)) it closes said program as well.  I know this is expected, and is very useful in other situations.  `selecta` does the same thing.

`selecta` also has a mapping to "cancel" the selection, though, which exits with a status of `0`.  In the `tig` example above this just closes `selecta` and brings you back into `tig`.

Is this feasible for `pick`?

**Comment by calleerlandsson** [comment]
Hey @rosshadden,

Do I understand this correctly? When you use `pick` from within `tig` and exit `pick` by pressing <kbd><kbd>Control</kbd>-<kbd>C</kbd></kbd>, `tig` also exits?

I think this is because of how `tig` is implemented to handle exit codes of programs it runs. For example running `pick` from within Vim and exiting by pressing <kbd><kbd>Control</kbd>-<kbd>C</kbd></kbd> does not exit Vim.

I'm definitely interested in solving this though! I could not find a description of the behavior you're referring to in the `selecta` README nor could I find the code supporting it. Could you describe it in more detail?

What mapping would be suitable for this functionality?
What would `pick` output when exiting?

**Comment by rosshadden** [comment]
I found it in the `selecta` history:  https://github.com/garybernhardt/selecta/issues/49#issuecomment-62595572

**Comment by calleerlandsson** [comment]
@rosshadden If I understand this correctly, the issue was not caused by the abort but rather by the mapping of it to <kbd>ESC</kbd>. This is because escape sequences start with <kbd>ESC</kbd> and to determine wether the user entered an escape sequence or an <kbd>ESC</kbd> we'd have to deal with timing.

If we map the abort function to a different key combination we would not have this issue.

It still seems like `selecta`, when aborted, would exit with a non-zero status, though? How is that different to how `pick` handles an interrupt?

**Comment by rosshadden** [comment]
I still think this should be added, I just can't think of a good key combination to use.

Maybe `alt-c` since it's similar to the existing `ctrl-c`?  That is, `^[c`, like how we used `^[Enter` for [using the current input](https://github.com/thoughtbot/pick/commit/d1f486a9b4cca9f7637b32112cb54364ebf75b99).

**Comment by calleerlandsson** [comment]
@rosshadden Would this be supported by pressing <kbd><kbd>Alt</kbd><kbd>Enter</kbd></kbd> without typing anything into pick when it starts?

**Comment by rosshadden** [comment]
No I was just saying `Alt-Enter` is an alt mapping we are already using. I'm proposing `Alt-c` to cancel, unless you have a better idea.

**Comment by calleerlandsson** [comment]
I'm hesitant in adding more key bindings in the interest of keeping the interaction simple.

Why does `tig` exit when `pick` exits with a non-zero status code?

Why does pressing <kbd><kbd>Alt</kbd><kbd>Enter</kbd></kbd> directly after launching `pick` (or <kbd><kbd>Ctrl</kbd><kbd>U</kbd></kbd><kbd><kbd>Alt</kbd><kbd>Enter</kbd></kbd> after typing something) not support this?

Are there other alternatives? Maybe providing an option to not treat canceling as an error, i.e. return a zero status code?

**Comment by rosshadden** [comment]
Oh I understand what you meant now.  Yeah, I guess I hadn't thought about that, but it does work perfectly.  Thanks!

**Comment by calleerlandsson** [comment]
Cool! I'm happy it works.
