### ISSUE TITLE
Use input directly

### ISSUE THREAD

**Issue by rosshadden** [thoughtbot/pick#58]
It would be quite useful if `pick` had a bind that used what the user currently has entered.
`dmenu` and some of its clones like `rofi` do this with `Control+Enter` or `Shift+Enter`, though those keys won't work well in the terminal.

This would let users select things that are not in the list.  Consider the following example, which lists local branches in a git repo:

```bash
git branch | cut -c 3- | pick | xargs git checkout
```

With the proposed feature, users could type in a commit hash or a tag, which would not be present in the list but are valid refs to checkout.  Or if a user has a bind like I do to "check out a branch if it exists, and otherwise make it", this would then be possible with `pick` alone.

**Comment by calleerlandsson** [comment]
Hey @rosshadden, thanks for your feedback.

This sounds like a cool idea. Am I understanding this correctly? The user would type something into pick to filter the results, then press a combination of keys. This would make pick output whatever the user typed regardless of whether it matched a choice or not?

**Comment by rosshadden** [comment]
Yeah, exactly.  The main idea is users can enter something not necessarily in the list.

I got the idea from `dmenu`, which is what many projects like this are inspired by.

**Comment by calleerlandsson** [comment]
Nice! Would you like to take a stab at adding this? If so, I'd be happy to give you pointers to where to start and answer your questions along the way!

**Comment by rosshadden** [comment]
Sure, I'd be happy to.

**Comment by calleerlandsson** [comment]
Great!

Shift+Enter and Ctrl+Enter sends the same character as Enter. I don't think this is a problem, though. We could actually use the same Enter key binding for this. What we could do to not alter the current functionality of pick, though, is to add a command line flag to turn this feature on.

Adding the flag is done in [`main.c`](https://github.com/thoughtbot/pick/blob/master/src/main.c).

An `int` saying whether or not the flag is present would have to be passed to `get_selected` here: https://github.com/thoughtbot/pick/blob/master/src/main.c#L59

In `ui.c` we could switch on this new `int` parameter: https://github.com/thoughtbot/pick/blob/master/src/ui.c#L243-L247

Since `get_selected` currently returns a pointer to a `struct choice` contained in the passed in `struct choices` we'll either have to figure out:

1. How we could return the current query as a `struct choice`.
2. How we can change `get_selected` to always return a `char *` and then return the current query if the flag is present.

I'd love your feedback on these ideas!

**Comment by rosshadden** [comment]
I don't think it should be hidden behind a flag.  The default behavior is still the most useful, which is to select the best-matching result when you hit `enter`.  I think it should just be a separate mapping to use the current input.

It sucks that terminals don't all support `shift+enter` or `ctrl+enter`, as nothing else makes as much sense (vim-wise).  What about `alt+enter`?  That sequence is sent correctly for me, in `urxvt`---does it work in all terminals?

**Comment by calleerlandsson** [comment]
I think it will work if the user is using alt or option as a meta key in their terminal emulator.

This will send two characters to pick: escape followed by enter.
