### ISSUE TITLE
Handling empty input

### ISSUE THREAD

**Issue by mattix** [thoughtbot/pick#62]
Should empty input be ignored or handled in some other way? Currently only CTRL+C will exit.

To reproduce:
echo -ne "" | pick

**Comment by calleerlandsson** [comment]
@mattix Great question! Sadly, I don't have a good answer for you. Do you have any ideas on how to best handle this?

**Comment by mattix** [comment]
Sure thing!

Maybe simplest solution which comes to mind would be adding:

```
if (!SLIST_EMPTY(choices)) {
	io_print_choice(
		ui_selected_choice(choices, query, use_alternate_screen),
		output_description);
}
```
to https://github.com/thoughtbot/pick/blob/master/src/main.c#L60

This way pick will do nothing and return nothing if input is empty.

**Comment by mattix** [comment]
This way:
https://github.com/mattix/pick/blob/master/src/main.c

**Comment by calleerlandsson** [comment]
That's a nice solution!

I wonder, though, if we should exit with an exit code indicating failure since we weren't able to produce any meaningful output? Maybe we could even print an error message on `stderr` saying pick requires input?

I guess it depends on the use case.

Do you have a specific use case for this behavior, @mattix?

@rosshadden, do you have any thoughts on this?

I think #58, might be sort of related. If we exit immediately unless we get input, the user won't be able to use the new feature in #61.

**Comment by rosshadden** [comment]
I think it's best to maintain consistent behavior. If the list is empty, it's still a list, it just has zero items. While I understand the motivation, I do not consider zero choices an "error", especially not one worthy of a nonzero exit code. 

Just my two cents.

**Comment by mattix** [comment]
I wouldn't print any error either. The only choice for empty list would be empty I guess.

**Comment by calleerlandsson** [comment]
@rosshadden, @mattix All good points.

@mattix, what would the use-case for this be? I have personally not run into this issue before.

**Comment by calleerlandsson** [comment]
@mattix do you have any ideas on what use-case this would support?

**Comment by calleerlandsson** [comment]
I'm going to close this due to inactivity.
